[endpoints.people]
url = "https://randomuser.me"
inference = "/api"
health = "/api"

[endpoints.yesno]
url = "https://yesno.wtf"
inference = "/api"
health = "/api"

[services.hello]
stages = [["people", "yesno"]]